spring.jmx:
   enabled: false

spring.datasource:
    url: jdbc:h2:mem:skip;MODE=MySQL

server:
  port: 8080

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8081
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: skipthedishes
  version: 0.0.1-SNAPSHOT
  description: skipthedishes
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

restaurant.service:
  name: 'default profile:'
---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop

restaurant.service:
  name: 'test profile:'
